version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: videos
      POSTGRES_USER: videos
      POSTGRES_PASSWORD: videos
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videos -d videos"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./data:/data
      - ./fonts:/fonts
      - ./assets:/app/assets:ro
    command: ["/bin/bash", "/app/docker/api-entrypoint.sh"]

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
